In [17]:
import pandas as pd
import numpy as nlp
from nltk.tokenize import sent_tokenize, word_tokenize
import os
import gensim
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords

Imported all the necessary library that are required for the completion of the exercise.

In [8]:
story=[]
for file in os.listdir('data'):
    
    f=open(os.path.join('data',file))
    corpus=f.read()
    raw_sent=sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

The actual file contains 5 seperate text files that contains the chapters of Game of thrones.

In [20]:
stop=set(stopwords.words('english'))

I have created a stop variable that consists all the stop-words from english literature.

In [22]:
new_story=[]
for i in range(len(story)):
    car=[]
    for j in story[i]:
        if j not in stop:
            car.insert(i,j)
    new_story.append(car)
new_story

[['around',
  'dark',
  'grow',
  'began',
  'woods',
  'urged',
  'gared',
  'back',
  'start',
  'prologue',
  'martin',
  'george',
  'fire',
  'ice',
  'song',
  'one',
  'book',
  'thrones',
  'game'],
 ['wildlings', 'dead'],
 ['dead', 'frighten'],
 ['ser', 'waymar', 'royce', 'smile', 'hint', 'asked'],
 ['gared', 'rise', 'bait'],
 ['old', 'man', 'past', 'fifty', 'seen', 'go', 'come', 'lordlings'],
 ['dead', 'dead', 'said'],
 ['business', 'dead'],
 ['dead'],
 ['royce', 'asked', 'softly'],
 ['proof'],
 ['saw', 'gared', 'said'],
 ['says', 'dead', 'proof', 'enough'],
 ['known', 'would', 'drag', 'quarrel', 'sooner', 'later'],
 ['wished', 'later', 'rather', 'sooner'],
 ['mother', 'told', 'dead', 'men', 'sing', 'songs', 'put'],
 ['wet', 'nurse', 'said', 'thing', 'royce', 'replied'],
 ['never', 'believe', 'anything', 'hear', 'woman', 'tit'],
 ['things', 'learned', 'even', 'dead'],
 ['voice', 'echoed', 'loud', 'twilit', 'forest'],
 ['page', 'long', 'ride', 'us', 'gared', 'pointed'],
 ['eig

The need for executing that kind of code is to make sure when the corpus will be inserted into **Word2Vec** function, for the funtion to work perfectly without giving any error I have to make sure that all the text are in kind of sentence tokenize format. That's the basic requrie of the funtion

In [55]:
model=gensim.models.Word2Vec(window=5,min_count=2)

Now here we are making the model with **window** as 5 that means in Word2Vec when the word counts will be selected it will be 2 words each as the labela dn 1 word in between would be target and **min_count** means that only consider the sentence tokenize that is ahving counts more than 2.

In [27]:
model.build_vocab(new_story)

In [28]:
model.train(new_story,total_examples=model.corpus_count,epochs=model.epochs)

(4396635, 4579390)

In [30]:
model.wv.most_similar('jon')

[('sam', 0.7316659688949585),
 ('theon', 0.683492124080658),
 ('ygritte', 0.6773587465286255),
 ('larence', 0.6665704250335693),
 ('grenn', 0.6602737903594971),
 ('pyp', 0.6566817760467529),
 ('asha', 0.6530099511146545),
 ('bran', 0.6493229269981384),
 ('tormund', 0.6446583867073059),
 ('ghost', 0.6362072825431824)]

In [32]:
model.wv.most_similar('daenerys')

[('myrcella', 0.8821197152137756),
 ('stormborn', 0.8671407103538513),
 ('princess', 0.8643463850021362),
 ('viserys', 0.8601998686790466),
 ('margaery', 0.8559591770172119),
 ('rhaegar', 0.8382079601287842),
 ('elia', 0.8372842073440552),
 ('consort', 0.8316493034362793),
 ('unburnt', 0.8307284712791443),
 ('daena', 0.8282771706581116)]

In [34]:
model.wv.doesnt_match(["jon",'rikon','robb','arya','sansa','bran'])

'jon'

In [36]:
model.wv.doesnt_match(['cersei','jaime','bronn','tyrion'])

'bronn'

In [38]:
model.wv['jon']

array([ 1.5787426 ,  1.1649584 ,  0.8809851 , -0.74041057, -0.6470287 ,
       -0.43617216, -1.1173427 , -0.6654257 ,  0.1585224 , -1.2462521 ,
        0.6575081 ,  1.5225064 , -0.1655143 , -0.5086055 ,  0.34747034,
        1.2258086 ,  0.840826  , -0.5343237 ,  0.29297307, -1.0884473 ,
        0.6048234 , -0.98730236, -0.04798796, -1.1414626 , -1.5201005 ,
       -1.3129032 , -1.1660763 , -0.46249253, -0.94719267,  0.35278285,
        1.5126405 , -0.01441816, -0.9015189 ,  0.20783263,  1.0814267 ,
        0.192413  , -1.1759733 ,  1.308337  , -0.5360352 , -1.362987  ,
        1.6200941 , -0.8964244 ,  0.12325244,  0.24523538,  1.9965926 ,
       -1.5120975 , -0.44180387, -0.37882903, -0.33146605,  1.0716149 ,
       -0.36923802, -0.11828992,  0.47783607,  0.45440602, -0.54570866,
        0.2794598 , -0.5348265 ,  0.20585656, -0.95753115,  0.76184547,
        0.94651246,  0.4937598 ,  0.58175284, -0.35138234,  0.81018037,
       -0.93080753, -0.15022771,  1.5633146 , -0.98802114,  1.58

In [40]:
model.wv['king']

array([-1.939913  , -0.86434525,  0.06272479, -0.01339137, -0.86109984,
        1.1944503 ,  1.6137111 , -0.11473978, -1.1181642 , -2.0678313 ,
        0.10049421, -1.116977  , -1.7406092 ,  1.9765962 , -1.5297183 ,
        0.8919097 ,  0.6424276 ,  0.1486735 ,  1.1402874 ,  0.32052317,
        1.1679646 ,  0.53013486, -0.31256425,  0.49385637, -0.45861214,
       -1.9182532 ,  0.5662876 , -0.74534506,  2.1109717 ,  1.7936354 ,
        0.76134324, -0.24469957,  0.61441755,  1.486505  ,  0.6544994 ,
       -0.13687843,  0.10811955, -0.34396192,  0.8664152 ,  0.13555817,
        0.37382603,  1.2117851 ,  1.2887825 ,  0.2409315 ,  0.34901014,
       -0.8835974 , -1.5444114 ,  1.5422293 ,  1.3714105 ,  1.5169165 ,
       -1.7495252 ,  1.525181  , -0.31402615, -0.14939523, -0.99858   ,
       -1.9696264 ,  0.252539  ,  1.0676223 , -1.0097983 ,  0.980827  ,
       -0.3005071 , -0.28723988,  0.4061395 , -0.35623017,  1.5684931 ,
       -1.8834945 , -1.3412358 , -0.1931318 , -1.0980222 ,  2.09

In [42]:
model.wv.similarity('arya','sansa')

0.8786286

In [43]:
model.wv.similarity('cersei','sansa')

0.71535444

In [44]:
model.wv.similarity('tywin','sansa')

0.36425316

In [45]:
model.wv.get_normed_vectors().shape

(17310, 100)

In [47]:
model.wv.get_normed_vectors()

array([[-0.15853934, -0.14610803,  0.01947305, ..., -0.10109182,
        -0.0664359 ,  0.17146084],
       [-0.06606658, -0.06629777,  0.11496511, ...,  0.03706719,
         0.00924871, -0.08485448],
       [-0.02801353,  0.01530611, -0.09733826, ..., -0.09227549,
        -0.04842496, -0.1304453 ],
       ...,
       [-0.0531497 ,  0.09875643,  0.12511458, ..., -0.23826778,
         0.17470996, -0.03891619],
       [-0.0992261 ,  0.09042615,  0.13811839, ..., -0.23943941,
         0.10511039,  0.01742393],
       [-0.03858672,  0.09889213,  0.14631875, ..., -0.20763245,
         0.10572255, -0.02671959]], dtype=float32)

In [48]:
y=model.wv.index_to_key
y

['said',
 'lord',
 'would',
 'one',
 'ser',
 'could',
 'man',
 'king',
 'men',
 'back',
 'well',
 'like',
 'jon',
 'father',
 'old',
 'hand',
 'even',
 'tyrion',
 'never',
 'know',
 'see',
 'made',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'long',
 'might',
 'us',
 'come',
 'face',
 'still',
 'head',
 'red',
 'way',
 'boy',
 'page',
 'must',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 'little',
 'took',
 'came',
 'though',
 'say',
 'three',
 'away',
 'dead',
 'son',
 'blood',
 'take',
 'go',
 'half',
 'make',
 'arya',
 'saw',
 'day',
 'white',
 'jaime',
 'first',
 'look',
 'want',
 'much',
 'enough',
 'sword',
 'tell',
 'girl',
 'bran',
 'great',
 'looked',
 'left',
 'knew',
 'asked',
 'gave',
 'maester',
 'called',
 'wall',
 'every',
 'heard',
 'sansa',
 'let',
 'yet',
 'went',
 'turned',
 'dany',
 'need',
 'behind',
 'around',
 'woman',
 'another',
 'snow',
 'beneath',
 'across',
 'knight',
 'keep',
 'grace',
 'found',
 'gold',
 'last',
 'cersei',
 'castle',
 '

In [49]:
 from sklearn.decomposition import PCA
pca=PCA(n_components=3)

In [51]:
model.wv.get_normed_vectors().shape

(17310, 100)

In [52]:
X=pca.fit_transform(model.wv.get_normed_vectors())
X

array([[-0.48042637,  0.09883989, -0.25008574],
       [-0.39797118,  0.48823172, -0.09636602],
       [-0.51994973, -0.2329514 ,  0.25464737],
       ...,
       [-0.00570098,  0.02943909,  0.0250609 ],
       [-0.13652459, -0.02379944, -0.06156132],
       [-0.09535541, -0.00597853, -0.0085207 ]], dtype=float32)

In [57]:
import plotly.express as px
fig=px.scatter_3d(X[:1000],x=0,y=1,z=2,color=y[:1000])
fig.show()

# Thank You