In [1]:
import pandas as pd
import numpy as nlp
from nltk.tokenize import sent_tokenize, word_tokenize
import os
import gensim
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords

Imported all the necessary library that are required for the completion of the exercise.

In [2]:
story=[]
for file in os.listdir('data'):
    
    f=open(os.path.join('data',file))
    corpus=f.read()
    raw_sent=sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

The actual file contains 5 seperate text files that contains the chapters of Game of thrones.

In [3]:
stop=set(stopwords.words('english'))

I have created a stop variable that consists all the stop-words from english literature.

In [8]:
new_story=[]
for i in range(len(story)):
    car=[]
    for j in story[i]:
        if j not in stop:
            car.insert(i,j)
    new_story.append(car)
new_story[:10]

[['around',
  'dark',
  'grow',
  'began',
  'woods',
  'urged',
  'gared',
  'back',
  'start',
  'prologue',
  'martin',
  'george',
  'fire',
  'ice',
  'song',
  'one',
  'book',
  'thrones',
  'game'],
 ['wildlings', 'dead'],
 ['dead', 'frighten'],
 ['ser', 'waymar', 'royce', 'smile', 'hint', 'asked'],
 ['gared', 'rise', 'bait'],
 ['old', 'man', 'past', 'fifty', 'seen', 'go', 'come', 'lordlings'],
 ['dead', 'dead', 'said'],
 ['business', 'dead'],
 ['dead'],
 ['royce', 'asked', 'softly']]

The need for executing that kind of code is to make sure when the corpus will be inserted into **Word2Vec** function, for the funtion to work perfectly without giving any error I have to make sure that all the text are in kind of sentence tokenize format. That's the basic requrie of the funtion

In [9]:
model=gensim.models.Word2Vec(window=5,min_count=2)

Now here we are making the model with **window** as 5 that means in Word2Vec when the word counts will be selected it will be 2 words each as the labels on 1 word in between would be target and **min_count** means that only consider the sentence tokenize that is having counts more than 2.

In [10]:
model.build_vocab(new_story)

In [11]:
model.train(new_story,total_examples=model.corpus_count,epochs=model.epochs)

(4396491, 4579390)

In [12]:
model.wv.most_similar('jon')

[('larence', 0.7405222058296204),
 ('surname', 0.6940242648124695),
 ('sam', 0.6884090304374695),
 ('theon', 0.6849839687347412),
 ('asha', 0.6518716216087341),
 ('ygritte', 0.6515383720397949),
 ('grenn', 0.6381540894508362),
 ('tormund', 0.618701159954071),
 ('reel', 0.6131207942962646),
 ('conceals', 0.6111812591552734)]

In [13]:
model.wv.most_similar('daenerys')

[('myrcella', 0.8780636787414551),
 ('viserys', 0.8667104840278625),
 ('stormborn', 0.8580858707427979),
 ('court', 0.8407610654830933),
 ('princess', 0.8406900763511658),
 ('unburnt', 0.8386623859405518),
 ('rhaegar', 0.8357021808624268),
 ('inseparable', 0.8314890265464783),
 ('margaery', 0.8289189338684082),
 ('elia', 0.8268024325370789)]

In [15]:
model.wv.doesnt_match(["jon",'rikon','robb','arya','sansa','bran'])

'jon'

In [16]:
model.wv.doesnt_match(['cersei','jaime','bronn','tyrion'])

'bronn'

In [17]:
#Output shows the feature values for word john, these values can be used to identify the closest words, matched,
#unmatched and other different analysis.
model.wv['jon']

array([-1.1994241 , -0.15534097,  1.6870474 , -1.4114228 ,  0.9018139 ,
        0.3712911 ,  0.29062793,  2.246836  ,  0.53350484, -1.3094747 ,
       -1.2429364 , -1.87427   , -0.6605846 , -0.6083961 , -0.7459157 ,
       -0.49164525,  0.09870175, -0.68083525,  0.35376585, -0.33182022,
       -1.0069995 ,  0.5077584 , -0.5330705 ,  0.01121842,  0.45444092,
        1.020459  , -1.6109833 ,  0.48211116,  0.51408863,  0.89731145,
       -1.1105112 , -0.39172164,  0.07722591, -0.06721469, -0.60034466,
       -0.55946434, -1.7448431 , -0.7464079 ,  0.9116971 , -0.34039953,
        0.25557777,  0.70863956, -0.04633668, -0.03491114, -1.0395776 ,
       -0.63805884,  0.6873231 , -1.0188662 , -0.36355138,  1.4481889 ,
        0.68469834, -1.1022791 ,  0.37346157, -1.2701956 ,  0.5512837 ,
       -0.80254334, -0.13385019,  1.1159726 ,  1.5573796 ,  2.1753383 ,
       -1.7849723 , -0.5941888 ,  0.8469572 , -0.29604033, -0.9016492 ,
        0.6255524 ,  1.6063608 ,  0.86143434,  0.25364143,  0.07

In [18]:
model.wv['king']

array([ 0.33954382, -0.4282738 ,  0.9510203 ,  1.8719543 , -1.2409998 ,
       -1.1374434 ,  0.22847192,  0.17258757, -0.32794017, -0.7633002 ,
        0.6517119 , -0.97240543, -0.17012218, -0.46973687, -0.35336658,
        0.6331869 ,  1.6563734 , -0.6360122 , -0.8169853 , -0.82213295,
       -0.18508059,  1.7143614 ,  0.3444466 , -3.0598586 ,  0.3230254 ,
        1.7203776 , -0.6311933 , -0.09684793, -1.5822799 ,  0.9685929 ,
       -1.0255592 ,  1.4188426 , -0.55068237, -1.2202235 , -0.873633  ,
        0.03975924, -1.195918  , -1.1488628 , -1.341247  ,  0.38111067,
        1.8418827 , -0.23406143, -0.80943114,  1.0604628 ,  1.0469545 ,
       -1.1057504 , -1.2684331 , -1.4459004 ,  2.2754483 ,  0.92494005,
       -1.7166276 , -0.28035563,  2.6353405 , -0.06819577, -0.72588086,
        1.932032  , -1.5765975 ,  1.1677059 , -0.64901376,  1.8589718 ,
        1.6823602 , -0.4014313 , -0.51960385,  0.9506451 , -0.48997456,
        0.62536   , -1.5194718 ,  1.9152652 ,  0.15418655, -0.46

In [19]:
model.wv.similarity('arya','sansa')

0.87578213

In [20]:
model.wv.similarity('cersei','sansa')

0.70275736

In [21]:
model.wv.similarity('tywin','sansa')

0.3444396

In [22]:
model.wv.get_normed_vectors().shape

(17310, 100)

In [26]:
model.wv.get_normed_vectors()

array([[-0.03598542,  0.08279129,  0.0902574 , ..., -0.05696455,
        -0.08802345,  0.1231163 ],
       [-0.13841237,  0.10324065,  0.18809877, ..., -0.11269848,
        -0.16010115,  0.15782233],
       [-0.01337584, -0.00279059,  0.0015807 , ..., -0.17981105,
         0.04609871, -0.08305715],
       ...,
       [-0.05272477,  0.14156641,  0.04823883, ..., -0.19059029,
         0.0544834 ,  0.0768777 ],
       [-0.15676756,  0.11110559,  0.16871147, ..., -0.15924254,
         0.06931706,  0.15807727],
       [-0.09120455,  0.08987091,  0.12109717, ..., -0.11464236,
         0.05514427,  0.0091886 ]], dtype=float32)

In [41]:
y=model.wv.index_to_key
y[:10]

['said', 'lord', 'would', 'one', 'ser', 'could', 'man', 'king', 'men', 'back']

In [42]:
 from sklearn.decomposition import PCA
pca=PCA(n_components=3)

In [43]:
model.wv.get_normed_vectors().shape

(17310, 100)

In [44]:
X=pca.fit_transform(model.wv.get_normed_vectors())
X

array([[ 0.46805662,  0.01256671,  0.26685902],
       [ 0.38237152,  0.44992238,  0.23415644],
       [ 0.51663506, -0.15830883, -0.2561245 ],
       ...,
       [ 0.15504998,  0.12211107,  0.0523327 ],
       [-0.02940854,  0.15007478,  0.29828423],
       [-0.16790943, -0.0375117 , -0.02152195]], dtype=float32)

In [46]:
import plotly.express as px
fig=px.scatter_3d(X[:100],x=0,y=1,z=2,color=y[:100])
fig.show()

# Thank You